pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
# pretrained_model_path: "./checkpoints/nitrosocke/mo-di-diffusion"
output_dir: "./outputs/boy_laptop_1"

train_data:
  video_path: "data/boy_laptop.mp4"
  prompt: "A boy with a spectacles on a couch uses a laptop"
  n_sample_frames: 24
  width: 128
  height: 128
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  prompts:
    - "A girl with a spectacles on a couch uses a laptop"
    - "A woman on a couch uses a laptop"
    - "A boy with a spectacles on a couch uses a mobile"
    - "A boy on a sofa uses an ipad"
  video_length: 24
  width: 128
  height: 128
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
