pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/cat-piano"

train_data:
  video_path: "data/cat-piano.mp4"
  prompt: "a cat is walking on a piano"
  n_sample_frames: 8
  width: 384
  height: 384
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  prompts:
    - "a tiger is walking on a piano"
    - "a dog is walking on a piano"
    - "a cat is walking on a piano, cartoon style"
  video_length: 8
  width: 384
  height: 384
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 1000
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
