pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/chicken"

train_data:
  video_path: "data/chicken.mp4"
  prompt: "a chicken pecks at the ground"
  n_sample_frames: 48
  width: 112
  height: 112
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  prompts:
    - "a chicken pecks from the ground"
    - "a dove pecks at the ground, eating something tasty."
    - "a dog eats from the ground"
  video_length: 48
  width: 112
  height: 112
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 1000
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True