pretrained_model_path: "./checkpoints/nitrosocke/mo-di-diffusion"
output_dir: "./outputs/ns_mallard_384_8"
train_data:
  video_path: "data/mallard-water.mp4"
  prompt: "a swan is swimming in the lake"
  n_sample_frames: 8
  width: 384
  height: 384
  sample_start_idx: 0
  sample_frame_rate: 1
validation_data:
  prompts:
    - "a duckling is swimming in the lake modern disney style"
    - "a duckling is swimming in the lake, cartoon style"
    - "a rabbit is swimming in the lake with blue water"
  video_length: 8
  width: 384
  height: 384
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50
learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 1000
validation_steps: 500
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"
seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True