keyframe:
- bbox_ratios:
  - 0.7
  - 0.35
  - 1.0
  - 0.65
  frame: 0
  prompt: A white horse galloping on a ground
- bbox_ratios:
  - 0.0
  - 0.35
  - 0.3
  - 0.65
  frame: 48
  prompt: A white horse galloping on a ground
token_inds:
- 1
- 2
- 3
width: 256
height: 256
seed : 5
num_inference_steps: 100
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.1
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.1
  temp_weaken_scale: 0.001
  trailing_length: 13

